### PR TITLE
Add cross-build with support of Scala 2.13.0

### PR DESCRIPTION
**Pull request by plokhotnyuk**

### CODE REVIEW

**Review by desmondyeung — APPROVED** [review]
Thanks for the contribution!

I was actually just starting to benchmark this with 2.13. I'm personally seeing performance regressions > 20% that I still haven't dug into.

**Comment by plokhotnyuk** [comment]
> I was actually just starting to benchmark this with 2.13. I'm personally seeing performance regressions > 20% that I still haven't dug into.

For which bench and params it can be reproduced?

**Comment by desmondyeung** [comment]
I'm not on my main laptop, but here are some results I just ran
```sbt
bench/jmh:run -i 3 -wi 3 -f1 XxHash64Bench.com_desmondyeung_hashing
```

2.12.9
```
[info] Benchmark                               (inputSize)   Mode  Cnt          Score         Error  Units
[info] XxHash64Bench.com_desmondyeung_hashing            8  thrpt    3  185778619.019 ± 1934781.573  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing          128  thrpt    3   56514066.010 ±  634268.161  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing          512  thrpt    3   23600141.441 ±  810006.785  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         1024  thrpt    3   13299685.393 ±  717831.068  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         1536  thrpt    3    9246722.872 ±  260972.021  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         2048  thrpt    3    7056145.724 ±  265236.056  ops/s
[success] Total time: 184 s, completed Aug 21, 2019, 3:15:13 PM
```

2.13.0
```
[info] Benchmark                               (inputSize)   Mode  Cnt          Score         Error  Units
[info] XxHash64Bench.com_desmondyeung_hashing            8  thrpt    3  184298585.739 ± 2062166.900  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing          128  thrpt    3   52045201.983 ± 3229937.845  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing          512  thrpt    3   21511399.488 ±  311140.849  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         1024  thrpt    3   11933307.339 ±  745263.751  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         1536  thrpt    3    8226233.328 ±  404379.004  ops/s
[info] XxHash64Bench.com_desmondyeung_hashing         2048  thrpt    3    6321480.430 ±  312725.166  ops/s
[success] Total time: 190 s, completed Aug 21, 2019, 3:11:30 PM
```

**Comment by desmondyeung** [comment]
I'll go ahead and merge this and open an issue.

Thanks again.

**Pull request merged**
